import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { Waypoint } from 'react-waypoint';
import { Button } from '../components/button';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Footer } from '../components/footer';
import { Header } from '../components/header';
import { HeroPost } from '../components/hero-post';
import { ArticleSVG, ChevronDownSVG } from '../components/icons';
import { Layout } from '../components/layout';
import { MorePosts } from '../components/more-posts';
import { Navbar } from '../components/navbar';
import { SecondaryPost } from '../components/secondary-post';
import {
	MorePostsByPublicationDocument,
	MorePostsByPublicationQuery,
	MorePostsByPublicationQueryVariables,
	PageInfo,
	PostFragment,
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
	PublicationFragment,
} from '../generated/graphql';
import { DEFAULT_COVER } from '../utils/const';

const SubscribeForm = dynamic(() =>
	import('../components/subscribe-form').then((mod) => mod.SubscribeForm),
);

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;

type Props = {
	publication: PublicationFragment;
	initialAllPosts: PostFragment[];
	initialPageInfo: PageInfo;
};

export default function Index({ publication, initialAllPosts, initialPageInfo }: Props) {
	const [allPosts, setAllPosts] = useState<PostFragment[]>(initialAllPosts);
	const [pageInfo, setPageInfo] = useState<Props['initialPageInfo']>(initialPageInfo);
	const [loadedMore, setLoadedMore] = useState(false);
	const [scrollY, setScrollY] = useState(0);
	const [isVisible, setIsVisible] = useState(false);

	useEffect(() => {
		setIsVisible(true);

		const handleScroll = () => {
			setScrollY(window.scrollY);
		};

		window.addEventListener('scroll', handleScroll);
		return () => window.removeEventListener('scroll', handleScroll);
	}, []);

	const loadMore = async () => {
		const data = await request<MorePostsByPublicationQuery, MorePostsByPublicationQueryVariables>(
			GQL_ENDPOINT,
			MorePostsByPublicationDocument,
			{
				first: 10,
				host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
				after: pageInfo.endCursor,
			},
		);
		if (!data.publication) {
			return;
		}
		const newPosts = data.publication.posts.edges.map((edge) => edge.node);
		setAllPosts([...allPosts, ...newPosts]);
		setPageInfo(data.publication.posts.pageInfo);
		setLoadedMore(true);
	};

	const scrollToBlog = () => {
		const blogSection = document.getElementById('blog-posts');
		blogSection?.scrollIntoView({ behavior: 'smooth' });
	};

	const firstPost = allPosts[0];
	const secondaryPosts = allPosts.slice(1, 4).map((post) => {
		return (
			<SecondaryPost
				key={post.id}
				title={post.title}
				coverImage={post.coverImage?.url || DEFAULT_COVER}
				date={post.publishedAt}
				slug={post.slug}
				excerpt={post.brief}
			/>
		);
	});
	const morePosts = allPosts.slice(4);

	return (
		<AppProvider publication={publication}>
			<Layout>
				<Head>
					<title>
						{publication.displayTitle || publication.title || 'RYEO LABS'}
					</title>
					<meta
						name="description"
						content={
							publication.descriptionSEO || publication.about?.text || 'Innovation • Research • Insights'
						}
					/>
					<meta property="twitter:card" content="summary_large_image" />
					<meta
						property="twitter:title"
						content={publication.displayTitle || publication.title || 'RYEO LABS'}
					/>
					<meta
						property="twitter:description"
						content={
							publication.descriptionSEO || publication.about?.text || 'Innovation • Research • Insights'
						}
					/>
					<meta
						property="og:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<meta
						property="twitter:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{
							__html: JSON.stringify(addPublicationJsonLd(publication)),
						}}
					/>
				</Head>
				<Header />

				{/* Hero Section - Full screen with video background */}
				<section
					className="relative flex min-h-screen items-center justify-center overflow-hidden"
					style={{
						backgroundColor: '#C20005'
					}}
				>
					{/* Video Background */}
					<video
						autoPlay
						loop
						muted
						playsInline
						preload="auto"
						className="absolute inset-0 h-full w-full object-cover"
						style={{ zIndex: 0 }}
					>
						<source src="/assets/videos/CC1_Iron-Man.mp4" type="video/mp4" />
					</video>

					{/* Dark overlay for text readability */}
					<div
						className="absolute inset-0 bg-black/40"
						style={{ zIndex: 1 }}
					/>

					{/* Animated gradient overlay */}
					<div
						className="absolute inset-0 opacity-10"
						style={{
							background: 'radial-gradient(circle at 50% 50%, rgba(255, 253, 243, 0.3) 0%, transparent 50%)',
							zIndex: 2
						}}
					/>
					<div
						className={`relative z-10 px-6 text-center transition-all duration-1000 ${
							isVisible ? 'translate-y-0 opacity-100' : 'translate-y-10 opacity-0'
						}`}
						style={{ zIndex: 3 }}
					>
						{/* Logo/Title */}
						<div className="mb-12 flex justify-center">
							<div className="text-[#FFFDF3]">
								<h1
									className="text-6xl font-bold md:text-8xl uppercase"
									style={{
										fontFamily: "'Swis721 Ex BT', sans-serif",
										lineHeight: '0.885',
										letterSpacing: '-0.06em'
									}}
								>
									{(publication.displayTitle || publication.title || 'RYEO LABS').toUpperCase()}
								</h1>
							</div>
						</div>

						{/* Tagline */}
						<p
							className="mb-16 text-xl text-[#FFFDF3] md:text-2xl"
							style={{
								fontFamily: "'Montserrat', sans-serif",
								lineHeight: '0.885'
							}}
						>
							{publication.descriptionSEO || publication.about?.text || 'Innovation • Research • Insights'}
						</p>

						{/* CTA Buttons */}
						<div className="flex flex-col items-center gap-6 sm:flex-row sm:justify-center">
							<button
								onClick={scrollToBlog}
								className="group relative overflow-hidden rounded-full border-2 border-[#FFFDF3] bg-transparent px-10 py-4 font-semibold text-[#FFFDF3] transition-all duration-300 hover:bg-[#C20005] hover:text-[#FFFDF3]"
								style={{ fontFamily: "'Montserrat', sans-serif" }}
							>
								<span className="relative z-10">Explore</span>
							</button>
						</div>
					</div>

					{/* Scroll indicator */}
					<div
						className="absolute bottom-10 left-1/2 -translate-x-1/2 animate-bounce cursor-pointer"
						onClick={scrollToBlog}
						style={{ zIndex: 3 }}
					>
						<ChevronDownSVG className="h-8 w-8 text-[#FFFDF3]" />
					</div>
				</section>

				{/* About / What is RYEO LABS Section */}
				<section
					id="about"
					className="min-h-screen py-20 flex items-center"
					style={{ backgroundColor: '#FFFDF3' }}
				>
					<div className="container mx-auto px-6">
						<div className="max-w-7xl mx-auto">
							{/* Two Column Layout: Text on Left, Image on Right */}
							<div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">

								{/* Left Column - Text Content */}
								<div>
									<h2
										className="mb-8 text-5xl font-bold md:text-6xl"
										style={{
											color: '#C20005',
											fontFamily: "'Alexandria', sans-serif",
											lineHeight: '0.885'
										}}
									>
										What is {publication.displayTitle || publication.title || 'RYEO LABS'}?
									</h2>

									<div className="space-y-6">
										{publication.about?.text && (
											<p
												className="text-xl text-gray-700 leading-relaxed md:text-2xl"
												style={{ fontFamily: "'Montserrat', sans-serif" }}
											>
												{publication.about.text}
											</p>
										)}

										{publication.about?.html && (
											<div
												className="text-lg text-gray-600 leading-relaxed md:text-xl prose prose-lg max-w-none"
												style={{ fontFamily: "'Montserrat', sans-serif" }}
												dangerouslySetInnerHTML={{ __html: publication.about.html }}
											/>
										)}

										{!publication.about?.text && !publication.about?.html && (
											<p
												className="text-xl text-gray-700 leading-relaxed md:text-2xl"
												style={{ fontFamily: "'Montserrat', sans-serif" }}
											>
												RYEO LABS is a creative space where innovation meets curiosity. We explore the intersection of technology, design, and human experience to build meaningful solutions.
											</p>
										)}
									</div>
								</div>

								{/* Right Column - Image */}
								<div className="relative">
									{/* Publication logo or placeholder */}
									<div
										className="rounded-3xl overflow-hidden shadow-2xl relative"
										//style={{ minHeight: '600px' }}
									>
										{publication.preferences.logo ? (
											<Image
												src="/assets/images/287ee78811e9fc82ef5145e7302ad1e5.jpg"
												alt="Anne Reyes"
												width={540}
												height={684}
												className="object-contain"
												style={{ background: 'none' }}
											/>
										) : (
											<div className="w-full h-full flex items-center justify-center text-[#FFFDF3] text-4xl font-bold" style={{ fontFamily: "'Alexandria', sans-serif" }}>
												{publication.displayTitle || publication.title || 'RYEO'}
											</div>
										)}
									</div>

									{/* Decorative element */}
									<div
										className="absolute -bottom-6 -right-6 w-32 h-32 rounded-full opacity-20 -z-10"
										style={{ backgroundColor: '#C20005' }}
									/>
								</div>

							</div>
						</div>
					</div>
				</section>

				{/* Blog Posts Section */}
				<section
					id="blog-posts"
					className="min-h-screen py-20"
					style={{ backgroundColor: '#FFFDF3' }}
				>
					<Container className="flex flex-col items-stretch gap-10 px-5 pb-10">
						<div className="mb-12 text-center">
							<h2
								className="mb-4 text-4xl font-bold md:text-5xl"
								style={{
									color: '#C20005',
									fontFamily: "'Alexandria', sans-serif",
									lineHeight: '0.885'
								}}
							>
								Explore
							</h2>
							<p
								className="text-lg text-gray-700 md:text-xl"
								style={{
									fontFamily: "'Montserrat', sans-serif",
									lineHeight: '0.885'
								}}
							>
								Discover our latest insights and stories
							</p>
						</div>

						{allPosts.length === 0 && (
							<div className="grid grid-cols-1 py-20 lg:grid-cols-3">
								<div className="col-span-1 flex flex-col items-center gap-5 text-center text-slate-700 dark:text-neutral-400 lg:col-start-2">
									<div className="w-20">
										<ArticleSVG clasName="stroke-current" />
									</div>
									<p className="text-xl font-semibold">
										Hang tight! We&apos;re drafting the first article.
									</p>
								</div>
							</div>
						)}

						{allPosts.length > 0 && (
							<>
								<div className="grid items-start gap-6 xl:grid-cols-2">
									<div className="col-span-1">
										{firstPost && (
											<HeroPost
												title={firstPost.title}
												coverImage={firstPost.coverImage?.url || DEFAULT_COVER}
												date={firstPost.publishedAt}
												slug={firstPost.slug}
												excerpt={firstPost.brief}
											/>
										)}
									</div>
									<div className="col-span-1 flex flex-col gap-6">{secondaryPosts}</div>
								</div>

								{morePosts.length > 0 && (
									<>
										<MorePosts context="home" posts={morePosts} />
										{!loadedMore && pageInfo.hasNextPage && pageInfo.endCursor && (
											<div className="flex w-full flex-row items-center justify-center">
												<Button
													onClick={loadMore}
													type="outline"
													icon={<ChevronDownSVG className="h-5 w-5 stroke-current" />}
													label="Load more posts"
												/>
											</div>
										)}
										{loadedMore && pageInfo.hasNextPage && pageInfo.endCursor && (
											<Waypoint onEnter={loadMore} bottomOffset={'10%'} />
										)}
									</>
								)}
							</>
						)}
					</Container>
				</section>

				{/* Newsletter Subscription */}
				{allPosts.length > 0 && (
					<section className="py-20" style={{ backgroundColor: '#FFFDF3' }}>
						<Container className="px-5">
							<div className="bg-primary-50 grid grid-cols-4 rounded-lg px-5 py-5 dark:bg-neutral-900 md:py-10">
								<div className="col-span-full md:col-span-2 md:col-start-2">
									<h2 className="text-primary-600 dark:text-primary-500 mb-5 text-center text-lg font-semibold">
										Subscribe to our newsletter for updates on the future!
									</h2>
									<SubscribeForm />
								</div>
							</div>
						</Container>
					</section>
				)}

				<Footer />
			</Layout>
		</AppProvider>
	);
}

export const getStaticProps: GetStaticProps<Props> = async () => {
	const data = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
		GQL_ENDPOINT,
		PostsByPublicationDocument,
		{
			first: 10,
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const publication = data.publication;
	if (!publication) {
		return {
			notFound: true,
		};
	}
	const initialAllPosts = publication.posts.edges.map((edge) => edge.node);

	return {
		props: {
			publication,
			initialAllPosts,
			initialPageInfo: publication.posts.pageInfo,
		},
		revalidate: 1,
	};
};
